### ISSUE TITLE
调用堆栈没有完整显示

### ISSUE THREAD

**Issue by jingzhishen** [JasonOldWoo/arm-backtrace#1]
在hi3518e平台上，编译后运行结果如下：
[root@dvrdvs nfs] # ./test
Hello!
nfp-3 assert....
1: ./test(_Z4dumpv+0x38) [0x8aa8]
2: ./test(_ZN1A5AFuncEv+0x20) [0x8d58]

看测试用例，好像并没有将完整的调用堆栈打印出来，不知哪里有问题？

**Comment by JasonOldWoo** [comment]
@jingzhishen 非常抱歉之前没有留意到您的问题，现在已经做出调整，尽管太晚了！
